# -*- coding: utf-8 -*-
"""lab_inaturalist_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v2LmVpKIxDPMVE46EoNkreb0qQHq-VZE

# Lab: Wrangling Wild Data with the iNaturalist API

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com)

**Course:** CS 2500 - Data Wrangling (Fall 2026)  
**Context:** Week 3, Class 1: REST API Fundamentals & Remote Data Workflows  
**Focus:** Discovery-Based API Exploration, Documentation Research, Nested JSON Ingestion, and Defensive Wrangling  

---

## Scenario
You have been contracted by the **Utah Division of Wildlife Resources (DWR)**. The regional biologists are studying urban encroachment and need a dataset of recent **Mule Deer** (*Odocoileus hemionus*) sightings within a **50-kilometer radius of Santaquin, Utah** (`39.9750° N, 111.7858° W`).

Their GIS mapping software requires clean, flat tabular data with standardized latitude and longitude columns.

Rather than downloading a static export file, your job is to query the live **iNaturalist API** to discover the appropriate parameters, ingest the last **300 observations**, handle the nested response structures, and produce a clean Pandas DataFrame ready for spatial mapping.

### Essential Documentation References
- **API Endpoint Documentation:** [iNaturalist API v1 Docs (`/observations`)](https://api.inaturalist.org/v1/docs/#!/Observations/get_observations)
- **API Usage Guidelines & Rate Limits:** [iNaturalist API Recommended Practices](https://www.inaturalist.org/pages/api+recommended+practices)
- **Taxon Search Reference:** [iNaturalist Taxa Search](https://www.inaturalist.org/taxa)

---

## Setup
Import the libraries needed to make HTTP requests, handle pauses, and structure data in DataFrames.
"""

# TODO: Import requests, time, and pandas
import requests
import time
import pandas as pd

"""---
## Part 1: Documentation Research & Parameter Discovery

When working with any new API, your first step is consulting the documentation to determine which endpoint and query parameters to use.

### Research Tasks
1. **Base Endpoint:** The v1 observations endpoint is `https://api.inaturalist.org/v1/observations`.
2. **Taxon Lookup:** How do we tell the API we only want Mule Deer?  
   - Look up "Mule Deer" (*Odocoileus hemionus*) on [iNaturalist Taxa](https://www.inaturalist.org/taxa). Find the numeric **Taxon ID**.
   - In the [API documentation](https://api.inaturalist.org/v1/docs/#!/Observations/get_observations), find which query parameter filters by this ID.
3. **Spatial Filtering:** Find the parameters used to define a circular search around a central coordinate (`lat`, `lng`, and `radius` in km).
4. **Pagination:** Find the parameter names for controlling the number of results returned per request and the page number.

### Action
Build your `params` dictionary and send a single exploratory `GET` request for **Page 1** (requesting 100 results per page around Santaquin: `lat = 39.9750`, `lng = -111.7858`, `radius = 50`).
"""

# TODO: Define the endpoint and params dictionary from your doc research, send the GET request, and check response.status_code
#https://api.inaturalist.org/v1/observations?taxon_id=42220&lat=39.975&lng=-111.7858&radius=50&order=desc&order_by=created_at
url = "https://api.inaturalist.org/v1/observations"
params = {"taxon_id":42220,
          "lat":39.975,
          "lng":-111.7858,
          "radius":50,
          }
req = requests.get(url, params=params)
print (req)

"""---
## Part 2: Inspecting the Response & "Discovering the Mess"

APIs do not return tidy flat spreadsheets; they return hierarchical JSON representations of application objects.

### Exploration Tasks
1. Convert the response to a Python dictionary using `response.json()`.
2. Print the top-level keys. Which key tells you the total number of matching records in the entire database? Which key contains the list of observation records for this page?
3. Extract the first observation record (`obs = data["results"][0]`).
4. Print `obs.keys()` and print a few nested fields (like `obs["user"]` and `obs["geojson"]`).

### 🔍 Key Discovery Question: The Coordinate Order
Look at `obs["geojson"]["coordinates"]`.
- What are the two numeric values?
- Which one is negative (`~-111.7`) and which is positive (`~39.9`)?
- In standard GeoJSON format, does index `0` represent **Latitude** or **Longitude**? What would happen to your map if you assumed index `0` was latitude?
"""

# TODO: Convert response to JSON, inspect top-level keys, and print fields of the first observation record
resp = req.json()
print(resp.keys())
first = resp["results"][0]
print(first.keys())
print(first["geojson"]["coordinates"])
print(first["user"])

"""---
## Part 3: Researching Rate Limits & Building the Pagination Loop

Before writing code that makes repeated requests to a server, ethical data wranglers check the API's rate limits.

### Research Tasks
1. Check the [iNaturalist API Recommended Practices](https://www.inaturalist.org/pages/api+recommended+practices).
2. What is the recommended request threshold (requests per minute or seconds per request)?
3. What HTTP error code will you receive if you exceed their request threshold?

### Implementation
1. We need **300 observations** in total. Since each page returns 100 observations, write a loop to fetch pages `1`, `2`, and `3`.
2. Accumulate all observation records into a single list called `all_observations`.
3. **Polite API Etiquette:** Use `time.sleep()` in your loop to pause between requests according to iNaturalist's guidelines.
4. Print progress updates as each page is retrieved.
"""

# TODO: Write a pagination loop across pages 1-3 with polite time.sleep() delays to collect 300 total observations into all_observations
page = 0
all_observations = resp["results"]
while page < 10:
  page = page + 1
  params["page"] = page
  time.sleep(1)
  print("requesting page", page)
  r = requests.get(url,params=params)
  if r.status_code == 200:
    resp = r.json()
    all_observations += ["results"]
    page = resp["page"]

print(len(all_observations))

"""---
## Part 4: Defensive Data Extraction & Flattening

Now that you have 300 nested observation dictionaries, extract only the fields needed by the Utah DWR spatial analysts:
- `observation_id` (numeric ID)
- `observed_on` (date string)
- `user_login` (username string from nested `user` dict)
- `latitude` (float)
- `longitude` (float)
- `place_guess` (location description string)
- `quality_grade` (e.g., "research", "needs_id")

### ⚠️ Defensive Programming Rules
1. Some observations might have private or obscured coordinates where `geojson` is `None` or `coordinates` is missing.
2. Some records might have deleted users or missing metadata.
3. **Do NOT use direct indexing** like `obs["geojson"]["coordinates"][0]` without checking, or your script will crash with a `KeyError` or `TypeError`!
4. Use `.get()` or safe conditionals so that missing values default to `None`.
"""

# TODO: Iterate through all_observations and safely extract fields into a flat_records list of dictionaries

"""---
## Part 5: The Final GIS-Ready DataFrame & Validation

### Tasks
1. Convert `flat_records` into a Pandas DataFrame named `df_deer`.
2. Run `df_deer.head(10)` to preview the extracted rows.
3. Run `df_deer.info()` to verify data types and non-null counts.
4. Run `df_deer.describe()` on `latitude` and `longitude` to verify your coordinates fall into the expected Utah range (~39.5°–40.5° N, ~-112.3°–-111.2° W).
"""

# TODO: Create df_deer DataFrame, inspect with .head(), .info(), and .describe()

"""---
## Part 6 (Bonus): Spatial Distribution Sanity Check
Generate a quick scatter plot of the extracted sighting coordinates to visually verify the spatial distribution around Santaquin.
"""

# TODO (Bonus): Plot latitude vs longitude as a scatter plot