# -*- coding: utf-8 -*-
"""10_miniutes_to_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEoAywq57DFGg0rIqmT3MDvrZmzaRo7t
"""

# Setup: import libraries
import numpy as np
import pandas as pd

# Remote dataset URL
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

# TODO: Load the Titanic dataset from the URL above into a variable named `titanic_df`
titanic_df = pd.read_csv(url)


# TODO: Display the DataFrame
print(titanic_df)

# TODO 1: Print / display the entire titanic_df
display(titanic_df)

# TODO 2: Display the first 5 rows using .head()
display(titanic_df.head())

# TODO 3: Display summary statistics of numeric columns using .describe()
display(titanic_df.describe())

# TODO 4: Call .info() to inspect data types and missing value counts
titanic_df.info()

# TODO 1: Select and display only the 'Name', 'Sex', 'Age', and 'Survived' columns
print("--- Column Selection ---")
display(titanic_df[['Name', 'Sex', 'Age','Survived']])


# TODO 2: Filter for surviving passengers (Survived == 1) into `survivors_df` and display the first 5 rows
print("\n--- Filter: Survivng Passengers---")
SurvivngPassengers = (titanic_df[titanic_df['Survived'] == 1])
display(SurvivngPassengers.head())


# TODO 3: Filter for first-class passengers who paid a fare > 100 into `first_class_wealthy_df` and display it
print("\n--- Filter: First-Class Wealthy Passengers---")
first_class_wealthy_df = (titanic_df[(titanic_df['Pclass'] == 1) & (titanic_df['Fare'] > 100)])
display(first_class_wealthy_df)

# TODO 1: Calculate the median age across all passengers
age_df = pd.to_numeric(titanic_df['Age'], errors='coerce')
median_age = age_df.median()
print(f"Median Age: {median_age}")

# TODO 2: Impute missing Age values with the median age
titanic_df['Age'] = titanic_df['Age'].fillna(median_age)



# TODO 3: Confirm no nulls remain in the Age column (print null count)
print("Credits Null Count after fillna:", titanic_df['Age'].isnull().sum())


# TODO 4: Create a new column `FamilySize` which is the sum of `SibSp` and `Parch`
titanic_df['FamilySize'] = titanic_df['SibSp'] + titanic_df['Parch']


# TODO 5: Display the first 5 rows with .head() to verify the new column
titanic_df.head()

# TODO 1: Calculate and print the overall survival rate (mean of 'Survived')
print("Overall Survival rate:", titanic_df['Survived'].mean() * 100,'%')


# TODO 2: Calculate survival rate grouped by 'Sex'
display(titanic_df.groupby('Sex')['Survived'].mean() * 100)


# TODO 3: Calculate survival rate grouped by both 'Pclass' and 'Sex'
display(titanic_df.groupby(['Pclass', 'Sex'])['Survived'].mean() * 100)


# TODO 4: Calculate the average 'Age' for each 'Pclass'
display(titanic_df.groupby('Pclass')['Age'].mean())